# List of URLs to monitor in Prometheus file_sd_configs format
- targets:
  - https://technative.eu
  - https://homeassistant.toorren.net:8123
  - https://vaultwarden.tools.technative.cloud
  - https://eu-north-1.signin.aws.amazon.com/oauth?client_id=arn%3Aaws%3Asignin%3A%3A%3Aconsole%2Fcanvas&code_challenge=-Rn-gbTtOVB9x_bmJv8C5-TblrVeYw-hAxG7DF0P1mE&code_challenge_method=SHA-256&response_type=code&redirect_uri=https%3A%2F%2Fconsole.aws.amazon.com%2Fconsole%2Fhome%3FhashArgs%3D%2523%26isauthcode%3Dtrue%26nc2%3Dh_si%26oauthStart%3D1761840005253%26src%3Dheader-signin%26state%3DhashArgsFromTB_eu-north-1_ebe043db3a0dabb1
  - https://2lumc.improvement-it.nl
  - https://2medipoint.improvement-it.nl
  - https://acc.2lumc.improvement-it.nl
  - https://acc.lumc2.improvement-it.nl
  - https://acc.medipoint.improvement-it.nl
  - https://acc.medipointvb.improvement-it.nl
  - https://alltrackmedical.improvement-it.nl
  - https://alltrackrrs.improvement-it.nl
  - https://alltrackrrs.acc.improvement-it.nl
  - https://alltrackrrs.dev.improvement-it.nl
  - https://alltrackrrs.test.improvement-it.nl
  - https://alltrackshell.improvement-it.nl
  - https://alltrackshell.pre.improvement-it.nl
  - https://alltrackshell.temporary.improvement-it.nl
  - https://alltrackshell.test.improvement-it.nl
  - https://alltrackwms.improvement-it.nl
  - https://asz-assets.improvement-it.nl
  - https://asz-assets.acc.improvement-it.nl
  - https://asz-assets.test.improvement-it.nl
  - https://asz.test.improvement-it.nl
  - https://asza-tst-01.improvement-it.nl
  - https://at3.improvement-it.nl
  - https://bhv.test.improvement-it.nl
  - https://bic.test.improvement-it.nl
  - https://bo.deltics.test.improvement-it.nl
  - https://bo.intern.improvement-it.nl
  - https://bo.radboud.improvement-it.nl
  - https://bo.radboud.test.improvement-it.nl
  - https://boilerplate.improvement-it.nl
  - https://cedrah.test.improvement-it.nl
  - https://deltics.test.improvement-it.nl
  - https://demo.medux.improvement-it.nl
  - https://digitaalvignet.test.improvement-it.nl
  - https://duravermeer.improvement-it.nl
  - https://duravermeer.test.improvement-it.nl
  - https://dynamicforms.test.improvement-it.nl
  - https://facilities.improvement-it.nl
  - https://flevokust.test.improvement-it.nl
  - https://gtw.lora.improvement-it.nl
  - https://gvbassets.improvement-it.nl
  - https://gvbassets.test.improvement-it.nl
  - https://gvbmrp.improvement-it.nl
  - https://gvbmrp.test.improvement-it.nl
  - https://hallmark.improvement-it.nl
  - https://hallmark.test.improvement-it.nl
  - https://heemstede.improvement-it.nl
  - https://heemstede.test.improvement-it.nl
  - https://hma-tst-01.improvement-it.nl
  - https://hrdz010.improvement-it.nl
  - https://hrt.acc.improvement-it.nl
  - https://hrt.test.improvement-it.nl
  - https://hrt.test.aws.improvement-it.nl
  - https://iit-prod-01.improvement-it.nl
  - https://iit-tst-01.improvement-it.nl
  - https://iit-vpn.improvement-it.nl
  - https://iits.improvement-it.nl
  - https://ikbeniris.improvement-it.nl
  - https://ikbeniris.test.improvement-it.nl
  - https://innovation.improvement-it.nl
  - https://integron.improvement-it.nl
  - https://integron.acc.improvement-it.nl
  - https://integron.test.improvement-it.nl
  - https://jdv.improvement-it.nl
  - https://jdv.acc.improvement-it.nl
  - https://jdv.test.improvement-it.nl
  - https://jdv.testintern.improvement-it.nl
  - https://kangaroo.improvement-it.nl
  - https://kangaroo.acc.improvement-it.nl
  - https://kangaroo.test.improvement-it.nl
  - https://kobout.test.improvement-it.nl
  - https://lora.improvement-it.nl
  - https://lumc.test.improvement-it.nl
  - https://lumc2.improvement-it.nl
  - https://maxtenten.improvement-it.nl
  - https://maxtenten.acc.improvement-it.nl
  - https://maxtenten.test.improvement-it.nl
  - https://medipoint.improvement-it.nl
  - https://medipointvb.improvement-it.nl
  - https://medux.improvement-it.nl
  - https://medux-old.improvement-it.nl
  - https://medux-rapportage.improvement-it.nl
  - https://medux.acc.improvement-it.nl
  - https://medux.aws.improvement-it.nl
  - https://medux.aws.test.improvement-it.nl
  - https://medux.test.improvement-it.nl
  - https://nike.test.improvement-it.nl
  - https://o.improvement-it.nl
  - https://p4t.improvement-it.nl
  - https://payments.improvement-it.nl
  - https://philips.improvement-it.nl
  - https://pnh.test.improvement-it.nl
  - https://poc.improvement-it.nl
  - https://portpaydemo.improvement-it.nl
  - https://presentatie.improvement-it.nl
  - https://prezero.improvement-it.nl
  - https://radboud.improvement-it.nl
  - https://radboud.test.improvement-it.nl
  - https://remo.improvement-it.nl
  - https://rrs.improvement-it.nl
  - https://rrs.acc.improvement-it.nl
  - https://rrs.aws.acc.improvement-it.nl
  - https://rrs.aws.dev.improvement-it.nl
  - https://rrs.aws.test.improvement-it.nl
  - https://rrs.data.improvement-it.nl
  - https://rrs.test.improvement-it.nl
  - https://rrs.test.aws.improvement-it.nl
  - https://rrs2.acc.improvement-it.nl
  - https://rrs2.test.improvement-it.nl
  - https://rrsnen.acc.improvement-it.nl
  - https://rrsnen.acc.aws.improvement-it.nl
  - https://rrsnen.test.improvement-it.nl
  - https://rrsnen.test.aws.improvement-it.nl
  - https://sab.improvement-it.nl
  - https://sab3.improvement-it.nl
  - https://sailwaterdicht.improvement-it.nl
  - https://shell.tenaz.improvement-it.nl
  - https://shelldeliveries.improvement-it.nl
  - https://shelldeliveries.dev.improvement-it.nl
  - https://shelldeliveries.migration.improvement-it.nl
  - https://shelldeliveries.test.improvement-it.nl
  - https://shellnam.migration.improvement-it.nl
  - https://spaarne.test.improvement-it.nl
  - https://ssl-test.improvement-it.nl
  - https://stork.improvement-it.nl
  - https://stork.test.improvement-it.nl
  - https://suez.test.improvement-it.nl
  - https://support.improvement-it.nl
  - https://temporary.improvement-it.nl
  - https://tenaz.improvement-it.nl
  - https://test.improvement-it.nl
  - https://test.2lumc.improvement-it.nl
  - https://test.2medipoint.improvement-it.nl
  - https://test.alltrackshell.improvement-it.nl
  - https://test.facilities.improvement-it.nl
  - https://test.kangaroo.improvement-it.nl
  - https://test.medipoint.improvement-it.nl
  - https://test.medipointvb.improvement-it.nl
  - https://test.medux.improvement-it.nl
  - https://test.rrs.improvement-it.nl
  - https://test1.improvement-it.nl
  - https://test2.improvement-it.nl
  - https://update.medux.improvement-it.nl
  - https://vaarwater.improvement-it.nl
  - https://vaarwater.acc.improvement-it.nl
  - https://vaarwater.old.improvement-it.nl
  - https://vaarwater.test.improvement-it.nl
  - https://vaarwaterorg.test.improvement-it.nl
  - https://vrzw.improvement-it.nl
  - https://vrzw.acc.improvement-it.nl
  - https://vrzw.test.improvement-it.nl
  - https://vumcbeds.test.improvement-it.nl
  - https://wassenburg.improvement-it.nl
  - https://websocket.improvement-it.nl
  - https://wilbertstek.improvement-it.nl
  - https://wp.improvement-it.nl
  - https://wzuveluwe.improvement-it.nl
  - https://wzuveluwe.acc.improvement-it.nl
  - https://wzuveluwe.test.improvement-it.nl
  - https://xml-alltrackrrs.improvement-it.nl
  - https://xml-alltrackrrs.acc.improvement-it.nl
  - https://xml-rrs.aws.acc.improvement-it.nl
  - https://xml-rrs.aws.test.improvement-it.nl
  - https://zaanstad.improvement-it.nl
  - https://zabbix.improvement-it.nl

